### ISSUE TITLE
Concurrent modification exception in Mercury 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Mercury#12]
[14:33:03 WARN]: [Mercury] Task #29 for Mercury v1.1.104 generated an exception                                                                 │·······························
java.util.ConcurrentModificationException                                                                                                       │·······························
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207) ~[?:1.8.0_72-internal]                                           │·······························
        at java.util.TreeMap$KeyIterator.next(TreeMap.java:1261) ~[?:1.8.0_72-internal]                                                         │·······························
        at vg.civcraft.mc.mercury.MercuryBukkitListener$2.run(MercuryBukkitListener.java:43) ~[?:?]                                             │·······························
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d97e08b-880a532]                   │·······························
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-d97e08b-8│·······························
80a532]                                                                                                                                         │·······························
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]                   │·······························
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by erocs** [comment]
http://build.civcraft.co/job/Mercury-master/72/
